import Head from 'next/head';
import Script from 'next/script';
import Image from 'next/image';
import { Ubuntu } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Step from '../src/components/Step';
import { stepsData } from '../data/step.data';
import { gte, lt, lte, map } from 'lodash';
import React from 'react';
import PersonalInfo from '../src/components/PersonalInfo';
import SelectPlan from '../src/components/SelectPlan';
import PickAddOns from '../src/components/PickAddOns';
import Summary from '../src/components/Summary';
import ThankYou from '../src/components/ThankYou';

const ubuntu = Ubuntu({ weight: ['400', '700'], subsets: ['latin'] });

export default function Home() {
  const [activeStep, setActiveStep] = React.useState(1);

  React.useEffect(() => {
    console.log(activeStep);
  }, [activeStep]);

  function checkStep() {
    switch (activeStep) {
      case 1: {
        return <PersonalInfo />;
      }
      case 2: {
        return <SelectPlan />;
      }
      case 3: {
        return <PickAddOns />;
      }
      case 4: {
        return <Summary />;
      }
      case 5: {
        return <ThankYou />;
      }
    }
  }

  function loadSteps() {
    return map(stepsData, (step, index) => {
      const { order, text } = step;
      return (
        <Step
          key={index}
          order={order}
          text={text}
          active={order === activeStep ? true : false}
        />
      );
    });
  }

  function handleNext() {
    setActiveStep(activeStep + 1);
  }

  function handleBack() {
    if (gte(activeStep, 2)) {
      setActiveStep(activeStep - 1);
    }
  }

  return (
    <>
      <Head>
        <title>Frontend Mentor | Multi-step form</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <main className={`${styles.main} ${ubuntu.className}`}>
        <div className='container d-flex h-100'>
          <div className='row justify-content-center align-self-center w-100'>
            <div className={`col-12 card ${styles.cardMain}`}>
              <div className='row h-100'>
                <div
                  className={`col-sm-3 p-4 m-4 ${styles.sidePanelBackground}`}
                >
                  {loadSteps()}
                </div>
                <div className='form-options-wrapper offset-1 col-sm-6 pt-5'>
                  {checkStep()}

                  {lte(activeStep, 4) ? (
                    <div className={`w-100 ${styles.formOptionsFooter}`}>
                      {gte(activeStep, 2) ? (
                        <button
                          className={`btn ${styles.btnCustom} btn-lg float-left`}
                          onClick={handleBack}
                        >
                          Go Back
                        </button>
                      ) : null}
                      <button
                        className={`btn ${styles.btnPrimaryCustom} btn-lg float-right`}
                        onClick={handleNext}
                      >
                        {`${lte(activeStep, 3) ? 'Next Step' : 'Confirm'}`}
                      </button>
                    </div>
                  ) : null}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className='attribution mt-5'>
          Challenge by{' '}
          <a href='https://www.frontendmentor.io?ref=challenge' target='_blank'>
            Frontend Mentor
          </a>
          . Coded by <a href='#'>Your Name Here</a>.
        </div>
      </main>
    </>
  );
}
